[package]
name = "stacker"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8.0" }
bevy_rapier2d = { version = "0.16.2", features = ["wasm-bindgen"] }
bevy-inspector-egui = "0.12"
